###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-mayikt-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka


####swagger相关配置
swagger:
  base-package: com.demo.member.service.impl
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”由汪磊练习使用
  version: 1.1
  terms-of-service-url: www.baidu.com
  contact:
    name: wanglei
    email: 768543036@qq.com