spring:
  #  application:
  #    name: app-mayikt-weixin
  redis:
    host: 192.168.234.226
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.40.70.177:3306/member

####打印MyBatias日志
logging:
  level:
  ### 开发环境使用DEBUG 生产环境info或者error
   com.demo.member.mapper: DEBUG