#### 整合freemarker
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  #        template-loader-path:
  #        - classpath: /templates
  application:
    name: app-mayikt-portal-pay-web
###服务注册到eureka地址
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8100/eureka
server:
  port: 8082
redis:
  hostname: 192.168.179.128
  port: 6379
