###服务启动端口号
server:
  port: 8500
###服务名称(服务注册到eureka名称)  
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka


  
spring:
  application:
    name:  app-mayikt-goods
  redis:
    host: 192.168.146.128
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
###数据库相关连接      
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.40.70.177:3306/goods?useUnicode=true&characterEncoding=UTF-8
  data:
    elasticsearch:
    ####集群名称
     cluster-name: elasticsearch-cluster
    ####地址 
     cluster-nodes: 192.168.146.128:9300
xuecheng:
  elasticsearch:
    hostlist: ${eshostlist:192.168.146.128:9200,192.168.146.128:9201}