server:
  port: 8080
  servlet:
    context-path: /xxl-sso-server

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

spring:
  application:
    name: app-mayikt-xxl-sso-server
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
xxl:
  sso:
    redis:
      address: redis://192.168.146.128:6379
      expire:
        minite: 1440
